onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - '@swc/core'
  - core-js
  - keytar
  - node-pty
  - sharp

allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  core-js: true
  keytar: true
  node-pty: true
  sharp: true
